Update e-mail notification in maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -37,7 +37,8 @@ jobs:
       - name: Extract error summary
         id: read-log
         run: |
-          echo "ERROR_SUMMARY=$(grep -i 'exception\|failure\|error' build.log | tail -n 1 | sed 's/\"/\\\"/g' || echo 'No errors found')" >> $GITHUB_ENV
+          ERROR_SUMMARY=$(grep -i 'exception\|failure\|error' build.log | tail -n 1 || echo 'No errors found')
+          echo "ERROR_SUMMARY=$ERROR_SUMMARY" >> $GITHUB_ENV
 
       - name: Send email notification
         uses: dawidd6/action-send-mail@v3
@@ -46,9 +47,13 @@ jobs:
           server_port: 465
           username: ${{ secrets.MAIL_USERNAME }}
           password: ${{ secrets.MAIL_PASSWORD }}
-          subject: "Github Actions - Build Failure!"
-          body: "Build of ${{github.repository}} FAILED!\n\nError Summary: ${{ env.ERROR_SUMMARY }}"
+          subject: "GitHub Actions - Build Failure!"
+          body: |
+            Build of ${{ github.repository }} FAILED!
+
+            **Error Summary:**
+            ${{ env.ERROR_SUMMARY }}
           to: wiktoria.bialasik05@gmail.com, chojniakkatarzyna@protonmail.com, mati.czechow@gmail.com
-          from: Luke Skywalker
+          from: IOLab Project
           
           
